---
base:
  data_dir: /home/jeanpierre/libra2/libra2/blob_and_config
  chain_id: default
  role: validator
  waypoint:
    from_config: "0:28337338d4936cc2b5fe2250f6f61fbbc249c43821ecd389dd2e14a8954055c4"
consensus:
  max_block_size: 1000
  contiguous_rounds: 2
  max_pruned_blocks_in_mem: 10000
  round_initial_timeout_ms: 1000
  proposer_type:
    type: leader_reputation
    active_weights: 99
    inactive_weights: 1
  safety_rules:
    backend:
      type: in_memory_storage
    service:
      type: thread
debug_interface:
  admission_control_node_debug_port: 6191
  metrics_server_port: 9101
  public_metrics_server_port: 9102
  address: 0.0.0.0
  libra_trace:
    sampling:
      txn: 1/100
      block: 1/1
execution:
  genesis_file_location: genesis.blob
  service:
    type: thread
logger:
  is_async: true
  chan_size: 256
  level: INFO
metrics:
  collection_interval_ms: 1000
  dir: metrics
  enabled: false
mempool:
  broadcast_transactions: true
  shared_mempool_tick_interval_ms: 50
  shared_mempool_backoff_interval_ms: 30000
  shared_mempool_batch_size: 100
  shared_mempool_max_concurrent_inbound_syncs: 100
  shared_mempool_min_broadcast_recipient_count: ~
  max_broadcasts_per_peer: 25
  capacity: 1000000
  capacity_per_user: 10000
  system_transaction_timeout_secs: 86400
  system_transaction_gc_interval_ms: 180000
rpc:
  address: "0.0.0.0:8080"
state_sync:
  chunk_limit: 250
  tick_interval_ms: 100
  long_poll_timeout_ms: 30000
  max_chunk_limit: 1000
  max_timeout_ms: 120000
  sync_request_timeout_ms: 60000
storage:
  address: "127.0.0.1:6666"
  backup_service_port: 7777
  dir: libradb/db
  grpc_max_receive_len: 100000000
  prune_window: 500000
test:
  auth_key: 1796824cdcc3ab205c25f260e15dc6705942d356f114089d4a46f2f3b0b15b52
  operator_private_key: da3599e23bd8dd79ce77578fc791a72323de545cf23bb1588e49d8a1e023f6f3
  consensus_private_key: 50e53de2ca2006b933a4053cf4766c20ff773570e4af2d9d6ebca5ef02a49840
  initialize_storage: true
  publishing_option: ~
upstream:
  primary_networks:
    - 5942d356f114089d4a46f2f3b0b15b52
  upstream_peers: []
  fallback_networks: []
validator_network:
  listen_address: /ip4/0.0.0.0/tcp/6180
  connectivity_check_interval_ms: 5000
  mutual_authentication: true
  network_peers: {}
  seed_peers:
    5942d356f114089d4a46f2f3b0b15b52:
      - /ip4/172.18.0.10/tcp/6180/ln-noise-ik/bc9e1e478585fa19da7e09de7031d1836357969f9807f58c954a4b8c84ed9a77/ln-handshake/0
  discovery_method:
    gossip:
      advertised_address: /ip4/172.18.0.10/tcp/6180
      discovery_interval_ms: 1000
  identity:
    type: from_config
    key: e8485074628c5cde1b9c58b70a90b7de778cbdfc6148044f4373008dacd9bc5d
    peer_id: 5942d356f114089d4a46f2f3b0b15b52
  network_id: validator